
services:
  smb-front:
    build:
      context: .
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

